require 'rake/rdoctask'
require 'darkfish-rdoc'
require 'spec/rake/spectask'

task :default => :spec

desc "Run all specifications and generate coverage report."
Spec::Rake::SpecTask.new("spec") do |t|
  t.spec_files = FileList[File.join(File.dirname(__FILE__), '/**/*_spec.rb')]
  t.rcov = true
  t.rcov_opts = ["-x", "../relax_client"]
end

desc "Generate RDoc documentation"
Rake::RDocTask.new do |t|
  t.title    = "WebJourney - Opensocial Proxy"
  t.main     = "README"
  t.rdoc_dir = "rdoc"
  t.rdoc_files.include("README", "lib/**/*.rb")
  t.options += [
        '-SHN',
        '-f', 'darkfish',  # This is the important bit
      ]
end
