require 'spec/rake/spectask'

task :default => :spec

desc "Run all specifications"
Spec::Rake::SpecTask.new("spec") do |t|
  t.spec_files = FileList['./**/*_spec.rb']
  t.rcov = true
  t.rcov_opts = ["-x", "../relax_client"]
end
