development:
  httpd:
    servername: webjourney.local
  couchdb:
    webjourney: http://admin:time2relax@localhost:5984/webjourney-development
    opensocial: http://admin:time2relax@localhost:5984/webjourney-development
  misc:
    import_test_fixtures : true

production:
  httpd:
    servername: www.webjourney.org
  couchdb:
    webjourney: http://admin:time2relax@localhost:5984/webjourney-production
    opensocial: http://admin:time2relax@localhost:5984/webjourney-production